# Config file for automatic testing at travis-ci.org

language: python
python: 2.7
sudo: false
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=flake8

script: tox -e $TOX_ENV

install:
    - pip install tox
